from constants.constants import *
import math

POPULATION_SIZE = 26
ITERATIONS = 300
DNA_SIZE = 5
CROSSOVER_RATE = 0.9
MUTATION_RATE = 0.05
ELITISM = bool(1)
ELITISM_COUNT = 2

SELECTION_METHOD = TOURNAMENT_SELECTION
TOURNAMENT_SIZE = 5

CROSSOVER_METHOD = TWO_POINT_CROSSOVER
SINGLE_POINT_CROSSOVER_INDEX = 3
TWO_POINT_CROSSOVER_INDICES = [1, 3]


def fitness(i):
    val = -(math.pow(i, 2)) + 7 * i
    return val
